### ISSUE TITLE
Remove dependency on kubectl

### ISSUE THREAD

**Issue by andygrove** [andygrove/ballista#14]
The code currently shells out to kubectl for certain operations, instead of just posting YAML directly to the k8s API.

**Comment by rrichardson** [comment]
It looks like the current usage of `kubectl apply` is restricted to the creation of new resources, and not altering existing resources. 
If this is the case, it is quite a bit easier than re-implementing `kubectl apply` which  detects the appropriate resource type, and runs a 3-way patch. 

If we just need to create pods ala https://github.com/andygrove/ballista/blob/master/src/cluster.rs#L113

We should be able to just use: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#create-55

**Comment by rrichardson** [comment]
I *think* that translates to https://docs.rs/k8s-openapi/0.4.0/k8s_openapi/api/core/v1/struct.CreateNamespacedPodOptional.html

**Comment by andygrove** [comment]
Thanks for the info @rrichardson

**Comment by andygrove** [comment]
Fixed in #55
