### ISSUE TITLE
Set up CICD

### ISSUE THREAD

**Issue by andygrove** [andygrove/ballista#6]

**Comment by dbcfd** [comment]
It looks like you're setting up circle?

If you want to use travis, it's fairly straightforward: https://docs.travis-ci.com/user/tutorial/

A travis.yml if you want a template: https://github.com/dbcfd/tls-async/blob/master/.travis.yml

This requires repo owner permissions to setup though.

**Comment by andygrove** [comment]
Builds are now running in Travis CI. Thanks for the suggestions @dbcfd

**Comment by andygrove** [comment]
https://travis-ci.com/andygrove/ballista
